/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.lankaonlinemart.view;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author kalana dapsara
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    private ArrayList<JPanel> allPanel = null;

    public home() {
        initComponents();
        showDate();
        showTime();
        loadDashBoard();

    }
    //System.out.println("allPanel"+allPanel.toString());

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        pnlDashbord = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        pnlCustomer = new javax.swing.JPanel();
        lblCustomers = new javax.swing.JLabel();
        pnlItem = new javax.swing.JPanel();
        lblItems = new javax.swing.JLabel();
        pnlOrders = new javax.swing.JPanel();
        lblOrders = new javax.swing.JLabel();
        pnlPlaceOrder = new javax.swing.JPanel();
        lblPlaceOrder = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlHome = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel2.setBackground(java.awt.Color.lightGray);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(8, 88, 138));
        jPanel3.setPreferredSize(new java.awt.Dimension(1920, 100));
        jPanel3.setLayout(null);

        pnlDashbord.setBackground(new java.awt.Color(8, 88, 138));
        pnlDashbord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDashbordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDashbordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDashbordMouseExited(evt);
            }
        });

        lblName.setBackground(new java.awt.Color(0, 0, 0));
        lblName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(240, 240, 240));
        lblName.setText("Home");

        javax.swing.GroupLayout pnlDashbordLayout = new javax.swing.GroupLayout(pnlDashbord);
        pnlDashbord.setLayout(pnlDashbordLayout);
        pnlDashbordLayout.setHorizontalGroup(
            pnlDashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashbordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDashbordLayout.setVerticalGroup(
            pnlDashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDashbordLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(lblName)
                .addContainerGap())
        );

        jPanel3.add(pnlDashbord);
        pnlDashbord.setBounds(44, 0, 77, 59);

        pnlCustomer.setBackground(new java.awt.Color(8, 88, 138));
        pnlCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlCustomerMouseExited(evt);
            }
        });

        lblCustomers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCustomers.setText("Customers");
        lblCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCustomersMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlCustomerLayout = new javax.swing.GroupLayout(pnlCustomer);
        pnlCustomer.setLayout(pnlCustomerLayout);
        pnlCustomerLayout.setHorizontalGroup(
            pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCustomers)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCustomerLayout.setVerticalGroup(
            pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustomerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCustomers)
                .addContainerGap())
        );

        jPanel3.add(pnlCustomer);
        pnlCustomer.setBounds(120, 0, 120, 59);

        pnlItem.setBackground(new java.awt.Color(8, 88, 138));
        pnlItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlItemMouseExited(evt);
            }
        });

        lblItems.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblItems.setText("Items");

        javax.swing.GroupLayout pnlItemLayout = new javax.swing.GroupLayout(pnlItem);
        pnlItem.setLayout(pnlItemLayout);
        pnlItemLayout.setHorizontalGroup(
            pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItemLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblItems)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlItemLayout.setVerticalGroup(
            pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlItemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblItems)
                .addContainerGap())
        );

        jPanel3.add(pnlItem);
        pnlItem.setBounds(240, 0, 104, 59);

        pnlOrders.setBackground(new java.awt.Color(8, 88, 138));
        pnlOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlOrdersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlOrdersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlOrdersMouseExited(evt);
            }
        });

        lblOrders.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOrders.setText("Orders");

        javax.swing.GroupLayout pnlOrdersLayout = new javax.swing.GroupLayout(pnlOrders);
        pnlOrders.setLayout(pnlOrdersLayout);
        pnlOrdersLayout.setHorizontalGroup(
            pnlOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOrders)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlOrdersLayout.setVerticalGroup(
            pnlOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOrdersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblOrders)
                .addContainerGap())
        );

        jPanel3.add(pnlOrders);
        pnlOrders.setBounds(340, 0, 85, 59);

        pnlPlaceOrder.setBackground(new java.awt.Color(8, 88, 138));
        pnlPlaceOrder.setForeground(new java.awt.Color(240, 240, 240));
        pnlPlaceOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPlaceOrderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlPlaceOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlPlaceOrderMouseExited(evt);
            }
        });

        lblPlaceOrder.setBackground(new java.awt.Color(219, 113, 7));
        lblPlaceOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPlaceOrder.setText("Place Order");

        javax.swing.GroupLayout pnlPlaceOrderLayout = new javax.swing.GroupLayout(pnlPlaceOrder);
        pnlPlaceOrder.setLayout(pnlPlaceOrderLayout);
        pnlPlaceOrderLayout.setHorizontalGroup(
            pnlPlaceOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlaceOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPlaceOrder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPlaceOrderLayout.setVerticalGroup(
            pnlPlaceOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPlaceOrderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPlaceOrder)
                .addContainerGap())
        );

        jPanel3.add(pnlPlaceOrder);
        pnlPlaceOrder.setBounds(420, 0, 130, 59);

        jPanel9.setBackground(new java.awt.Color(8, 88, 138));
        jPanel9.setForeground(new java.awt.Color(240, 240, 240));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel9MouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/lankaonlinemart/Image/shutdown_30px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel9);
        jPanel9.setBounds(1820, 0, 86, 59);

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDate.setForeground(new java.awt.Color(240, 240, 240));
        jPanel3.add(lblDate);
        lblDate.setBounds(1430, 20, 200, 22);

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTime.setForeground(new java.awt.Color(240, 240, 240));
        jPanel3.add(lblTime);
        lblTime.setBounds(1670, 20, 150, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/lankaonlinemart/Image/calendar_50px.png"))); // NOI18N
        jPanel3.add(jLabel8);
        jLabel8.setBounds(1380, 10, 60, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/lankaonlinemart/Image/clock_50px.png"))); // NOI18N
        jPanel3.add(jLabel9);
        jLabel9.setBounds(1620, 10, 62, 40);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Lanka Online Mart SL");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(740, 20, 340, 30);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 59));

        pnlHome.setBackground(new java.awt.Color(34, 36, 36));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        jPanel2.add(pnlHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1920, 1000));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCustomerMouseEntered

    }//GEN-LAST:event_pnlCustomerMouseEntered

    private void pnlCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCustomerMouseExited

    }//GEN-LAST:event_pnlCustomerMouseExited

    private void pnlItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlItemMouseEntered

    }//GEN-LAST:event_pnlItemMouseEntered

    private void pnlOrdersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlOrdersMouseEntered

    }//GEN-LAST:event_pnlOrdersMouseEntered

    private void pnlPlaceOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPlaceOrderMouseEntered

    }//GEN-LAST:event_pnlPlaceOrderMouseEntered

    private void pnlDashbordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashbordMouseEntered

    }//GEN-LAST:event_pnlDashbordMouseEntered

    private void pnlDashbordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashbordMouseExited

    }//GEN-LAST:event_pnlDashbordMouseExited

    private void pnlItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlItemMouseExited

    }//GEN-LAST:event_pnlItemMouseExited

    private void pnlOrdersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlOrdersMouseExited

    }//GEN-LAST:event_pnlOrdersMouseExited

    private void pnlPlaceOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPlaceOrderMouseExited

    }//GEN-LAST:event_pnlPlaceOrderMouseExited

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseExited

    }//GEN-LAST:event_jPanel9MouseExited

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseEntered

    }//GEN-LAST:event_jPanel9MouseEntered

    private void pnlCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCustomerMouseClicked
        try {

            CustomerForm customerForm = new CustomerForm();
            pnlHome.removeAll();
            customerForm.setSize(pnlHome.getSize());
            pnlHome.add(customerForm);
            customerForm.repaint();
            customerForm.revalidate();

            lblCustomers.setForeground(new Color(240, 240, 240));
            lblName.setForeground(new Color(0, 0, 0));
            lblItems.setForeground(new Color(0, 0, 0));
            lblOrders.setForeground(new Color(0, 0, 0));
            lblPlaceOrder.setForeground(new Color(0, 0, 0));

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_pnlCustomerMouseClicked

    private void pnlItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlItemMouseClicked
        try {
            ItemForm itemForm = new ItemForm();
            pnlHome.removeAll();
            itemForm.setSize(pnlHome.getSize());
            pnlHome.add(itemForm);
            itemForm.repaint();
            itemForm.revalidate();

            lblItems.setForeground(new Color(240, 240, 240));
            lblCustomers.setForeground(new Color(0, 0, 0));
            lblName.setForeground(new Color(0, 0, 0));
            lblOrders.setForeground(new Color(0, 0, 0));
            lblPlaceOrder.setForeground(new Color(0, 0, 0));

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_pnlItemMouseClicked

    private void pnlOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlOrdersMouseClicked
        OrdersForm ordersForm = new OrdersForm();
        pnlHome.removeAll();;
        ordersForm.setSize(pnlHome.getSize());
        pnlHome.add(ordersForm);
        ordersForm.repaint();
        ordersForm.revalidate();

        lblOrders.setForeground(new Color(240, 240, 240));
        lblCustomers.setForeground(new Color(0, 0, 0));
        lblName.setForeground(new Color(0, 0, 0));
        lblItems.setForeground(new Color(0, 0, 0));
        lblPlaceOrder.setForeground(new Color(0, 0, 0));


    }//GEN-LAST:event_pnlOrdersMouseClicked

    private void pnlPlaceOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPlaceOrderMouseClicked
        PlaceOrderForm placeOrderForm = new PlaceOrderForm();
        pnlHome.removeAll();
        placeOrderForm.setSize(pnlHome.getSize());
        pnlHome.add(placeOrderForm);
        placeOrderForm.repaint();
        placeOrderForm.revalidate();

        lblPlaceOrder.setForeground(new Color(240, 240, 240));
        lblCustomers.setForeground(new Color(0, 0, 0));
        lblName.setForeground(new Color(0, 0, 0));
        lblItems.setForeground(new Color(0, 0, 0));
        lblOrders.setForeground(new Color(0, 0, 0));


    }//GEN-LAST:event_pnlPlaceOrderMouseClicked

    private void pnlDashbordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashbordMouseClicked

        lblName.setForeground(new Color(240, 240, 240));

        lblCustomers.setForeground(new Color(0, 0, 0));
        lblItems.setForeground(new Color(0, 0, 0));
        lblOrders.setForeground(new Color(0, 0, 0));
        lblPlaceOrder.setForeground(new Color(0, 0, 0));
        loadDashBoard();


    }//GEN-LAST:event_pnlDashbordMouseClicked

    private void lblCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomersMouseClicked

    }//GEN-LAST:event_lblCustomersMouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        this.setVisible(false);
        Login login = new Login();
        login.setVisible(true); 
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblCustomers;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblItems;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrders;
    private javax.swing.JLabel lblPlaceOrder;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel pnlCustomer;
    private javax.swing.JPanel pnlDashbord;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlItem;
    private javax.swing.JPanel pnlOrders;
    private javax.swing.JPanel pnlPlaceOrder;
    // End of variables declaration//GEN-END:variables

    private void loadDashBoard() {
        DashboardForm dashboardView = new DashboardForm();
        pnlHome.removeAll();
        dashboardView.setSize(pnlHome.getSize());
        pnlHome.add(dashboardView);
        dashboardView.repaint();
        dashboardView.revalidate();
    }

    private void showDate() {
        Date date = new Date();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        lblDate.setText(simpleDateFormat.format(date));
    }

    private void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date date = new Date();
                SimpleDateFormat simpleDateFormat = new SimpleDateFormat("hh:mm:ss a");
                lblTime.setText(simpleDateFormat.format(date));
            }
        }).start();
    }

}
